### ISSUE TITLE
data for comparing performance of classification approaches

### ISSUE THREAD

**Issue by GavinHuttley** [BenKaehler/q2-feature-classifier#10]
Compare blast, uclust and rdp (see qiime 1).

[Mock Data](https://github.com/caporaso-lab/mockrobiota)

**Comment by BenKaehler** [comment]
focus on naïve bayes first

**Comment by GavinHuttley** [comment]
Here is [the preprint](https://peerj.com/preprints/934/), [greg's comparison framework](https://github.com/gregcaporaso/short-read-tax-assignment/) and the [mockrobiota data](https://github.com/caporaso-lab/mockrobiota).

**Comment by GavinHuttley** [comment]
Start with mock-6 from  [mockrobiota data](https://github.com/caporaso-lab/mockrobiota). Note additional real data set from [this paper](http://www.pnas.org/content/107/14/6477.full), with [sequence file](https://github.com/caporaso-lab/q2d2/blob/master/example-data/keyboard/q191/rep-set.fna), [corresponding OTU table](https://github.com/caporaso-lab/q2d2/blob/master/example-data/keyboard/q191/otu-table.tsv) and [sample metadata](https://github.com/caporaso-lab/q2d2/blob/master/example-data/keyboard/sample-md.tsv).

These sequences were generated using plus 27F, 338R primers, whose sequences from [the paper](http://www.pnas.org/content/105/46/17994.full) are below. Those sequences contain an adapter, so do a smith-waterman alignment to find the 454 adapter.

"The forward primer (5′-GCCTTGCCAGCCCGCTCAGTCAGAGTTTGATCCTGGCTCAG-3′) contained the 454 Life Sciences primer B, the broadly conserved bacterial primer 27F, and a 2-base linker sequence ("TC"). The reverse primer (5′-GCCTCCCTCGCGCCATCAGNNNNNNNNNNNNCATGCTGCCTCCCGTAGGAGT-3′) contained the 454 Life Sciences primer A, the bacterial primer 338R, a "CA" inserted as a linker between the barcode and the rRNA primer, and a unique 12-bp error-correcting Golay barcode used to tag each PCR product (designated by NNNNNNNNNNNN; see Table S3)."

**Comment by BenKaehler** [comment]
@GavinHuttley I might be going crazy, but I can't find the actual reads in the mockrobiota data. What am I missing? Thanks.

**Comment by BenKaehler** [comment]
@BenKaehler don't forget to obtain unfiltered greengenes reference alignments

**Comment by GavinHuttley** [comment]
@BenKaehler look at [this file](https://github.com/caporaso-lab/mockrobiota/blob/master/data/mock-6/dataset-metadata.tsv), the `raw-data-url` field identifies an ftp site for downloading the raw data from.

**Comment by BenKaehler** [comment]
Thanks @GavinHuttley!

**Comment by BenKaehler** [comment]
I think we'll just use the analyses and data available in BenKaehler/short-read-tax-assignment.
