### ISSUE TITLE
create conda package

### ISSUE THREAD

**Issue by BenKaehler** [BenKaehler/q2-feature-classifier#11]
follow the wiki then seek help on slack

**Comment by BenKaehler** [comment]
@gregcaporaso, is this something that we should do?

**Comment by gregcaporaso** [comment]
Definitely. Do you want to get started, or would you like us to help out?
We've got a bunch of experience with conda release, and they can be kind of
painful, so if you hit any issues you should just get in touch about it.

**Comment by BenKaehler** [comment]
Thanks @gregcaporaso, happy to look at it ourselves, or for Nick to. Last time we spoke about this it sounded like you were moving away from conda, so I just wanted to make sure that it was still your favoured method of distribution.

**Comment by gregcaporaso** [comment]
It will be for the short term (at least the next several months). This
wouldn't be something that Nick would work on, but rather the usual QIIME
devs that you've been working with (Nick hasn't been involved in the conda
releases, but rather is looking for some Python programming tasks).

Want to take a first crack at it, and let us know if you need help? We can
get it added to the qiime2 conda channel when you're ready.

**Comment by BenKaehler** [comment]
No worries. I'll do this next.

**Comment by BenKaehler** [comment]
@gregcaporaso, are there any plans to update the [conda publication instructions](https://github.com/qiime2/qiime2/wiki/Publishing-a-plugin-on-conda) on the qiime2 wiki, or should I try to figure it out from scratch? Thanks!

**Comment by gregcaporaso** [comment]
We can help out with it if you want, we're planning to work on releases
next Wed and Thurs, so if you want to wait until then that's OK.

**Comment by BenKaehler** [comment]
Thanks @gregcaporaso, that sounds like the most efficient solution.

**Comment by BenKaehler** [comment]
Done in a7ca29e. Thanks @thermokarst, @ebolyen, and @gregcaporaso.
