### ISSUE TITLE
possible to remove depth parameter? 

### ISSUE THREAD

**Issue by gregcaporaso** [BenKaehler/q2-feature-classifier#2]
usually these just make as specific of assignments as they can.

**Comment by gregcaporaso** [comment]
Hey Ben, I think it's really important to support Naive Bayes and SVM in
the first release of this. Could you take the RDP approach, but classify to
the species level (rather than genus level) and treat the species level
taxonomy as the full taxonomy string (e.g., "k__bacteria; p__bacteroidetes;
... s__"). That's going to be really important for comparison to other
methods, and you're basically there already. Once you have that, we should
work with you to get a release up on conda. Then, I think adding some of
the multioutput-multiclass classifiers and assessing their accuracy could
be really good. No one is using those for taxonomic classification as far
as I know, so that'd be novel for a publication.

**Comment by BenKaehler** [comment]
Thanks Greg, ok, I'll concentrate on getting the conda release done then revisit this issue. If I can get default parameters working easily I'll make it a default parameter (set to seven). Otherwise I'll just remove the code.

**Comment by gregcaporaso** [comment]
@BenKaehler, one other note: you're working with the Greengenes reference right now, which has seven levels, but that's not always the case (for example, so taxonomies will include sub-levels, like sub-class, sub-phylum, etc). What if you just defaulted to always doing the deepest assignment possible with a given reference taxonomy? Then we could have a pipeline that filters the reference taxonomy if you want less specific assignments.

**Comment by BenKaehler** [comment]
Ok, I'll just take it out.

**Comment by BenKaehler** [comment]
Done in commit e15278d5be25dfd9d2c641334de4a5d4320c3143
