### ISSUE TITLE
testing and linting

### ISSUE THREAD

**Issue by gregcaporaso** [BenKaehler/q2-feature-classifier#5]
Add unit tests, travisci testing and I also recommend adding linting with flake8. See [``.travis.yml`` from QIIME 2](https://github.com/qiime2/qiime2/blob/62f878b6bddad943a0651e1d51fdc2a00007803e/.travis.yml) for an example.

**Comment by BenKaehler** [comment]
Set up with travis. Passed first time! For future reference:

https://travis-ci.org/BenKaehler/q2-feature-classifier

Now to write some unit tests...
